In [2]:
import numpy as np

In [3]:
X = 2 * np.random.rand(100,1)
y = 4 + 3 * X + np.random.randn(100, 1)

In [4]:
# getting the linear regression algorithm parameters using the normal equation
X_b = np.c_[np.ones((100, 1)), X] # this is basically to introduce a bias row filled with ones.
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)
print(theta_best)

[[3.89213847]
 [3.03927626]]


In [5]:
# using obtained parameters to predict for new values
X_new = np.array([[0], [2]])
X_new_b = np.c_[np.ones((2, 1)), X_new]
y_predict = X_new_b.dot(theta_best)
print(y_predict)

[[3.89213847]
 [9.97069099]]


In [6]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X, y)
lin_reg.intercept_, lin_reg.coef_
lin_reg.predict(X_new)

print(np.eye(6)*(1-1e-4))

[[0.9999 0.     0.     0.     0.     0.    ]
 [0.     0.9999 0.     0.     0.     0.    ]
 [0.     0.     0.9999 0.     0.     0.    ]
 [0.     0.     0.     0.9999 0.     0.    ]
 [0.     0.     0.     0.     0.9999 0.    ]
 [0.     0.     0.     0.     0.     0.9999]]
